const contractAddress = "0x0074FBe632E3423295146c601568CBD560299507"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Kawaii Anime Girls Club";
const welcome_h2 = "Connect to MetaMask to Get Started!";
/*const welcome_p = 'The Kawaii Anime Girls Club is a private web3 place on the blockchain where you can meet your Kawaii Anime Girl. Each of them have her own background story, character and look. They are all AI backed and are learning from the owner, so that they will be more unique with every interaction.';*/
const h1_presale_coming_soon = "Kawaii Anime Girls getting ready!!";
const h1_presale_mint = "Pre-Sale Minting Open!";
const h1_public_mint = "Public Minting Open!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to get every Kawaii Anime Girl ready. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted to meet a Kawaii Anime Girl.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist to meet a Kawaii Anime Girl 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist Kawaii Anime Girls. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public meeting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Meet your Kawaii Anime Girl";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Meet your Kawaii Anime Girl";
const mint_failed = "Relationship agreement failed. 😢 Please try again.";
