const contractAddress = ""; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Kawaii Anime Girls Club";
const welcome_h2 = "Connect to MetaMask to Get Started!";
/*const welcome_p = 'The Kawaii Anime Girls Club is a private web3 place on the blockchain where you can meet your Kawaii Anime Girl. Each of them have her own background story, character and look. They are all AI backed and are learning from the owner, so that they will be more unique with every interaction.';*/
const h1_presale_coming_soon = "Kawaii Anime Girls are getting ready!!";
const h1_presale_mint = "Pre-Sale Minting Open!";
const h1_public_mint = "Kawaii Anime Girls are ready!";
const h2_presale_coming_soon = " ";
const h2_presale_mint = "Public Meeting Countdown";
const p_presale_coming_soon = " ";
const p_presale_mint_not_whitelisted = "You are not whitelisted to meet a Kawaii Anime Girl.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist to meet a Kawaii Anime Girl 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist Kawaii Anime Girls. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public meeting is now open! 👫🏼";
const button_presale_coming_soon = "Join the Kawaii Anime Girls Club";
const button_presale_mint_whitelisted = "Meet your Kawaii Anime Girl!";
const button_presale_mint_not_whitelisted = "Join the Kawaii Anime Girls Club";
const button_presale_already_minted = "Join the Kawaii Anime Girls Club";
const button_public_mint = "Meet your Kawaii Anime Girl";
const mint_failed = "Relationship agreement failed. 😢 Please try again.";
